# Slice 2: The site tells the two-file shape
# Source: docs/superpowers/specs/2026-09-08-batch-collections-slices.md
# Recorded: 2026-09-08 against commit 7bbd6cf
#
# UAT: open Price a book, read the new "Risks with items" section, follow its
# link to Command line, find the home command with the jewellery file, and
# run it — the same three priced rows as slice 1's UAT.
#
# The acceptance criteria are almost entirely "the site says X, not Y" —
# this file re-drives the UAT command live, then asserts the documented
# pages carry the two-file shape and no page still claims items can't be
# batched, rather than re-testing batch's behaviour (already covered by
# tests/test_cli.py and slice 1's UAT).
import csv
import io
import unittest
from decimal import Decimal
from pathlib import Path

from tests.test_cli import run

ROOT = Path(__file__).resolve().parent.parent.parent
HOME = ROOT / "examples" / "home.ipn"
HOME_RISKS = ROOT / "examples" / "home-risks.csv"
HOME_ITEMS = ROOT / "examples" / "home-specified-items.csv"

DOCS = ROOT / "docs"
BOOK = (DOCS / "book.md").read_text()
CLI = (DOCS / "cli.md").read_text()

FORBIDDEN = "cannot be given in a batch"


def hand_written_pages():
    """Every .md under docs/, excluding generated examples/templates and the spec tree."""
    for path in DOCS.rglob("*.md"):
        rel = path.relative_to(DOCS).as_posix()
        if rel.startswith("superpowers/"):
            continue
        if rel.startswith("examples/") or rel.startswith("templates/"):
            continue  # generated by scripts/site_pages.py, covered separately
        yield path


class TheSiteTellsTheTwoFileShape(unittest.TestCase):
    def test_uat_price_a_book_links_to_the_command_that_prices_the_home_book(self):
        """Steps 1-3: Price a book keeps the live comparison, gains "Risks with
        items" naming the home files and a link to Command line; that command,
        run for real, produces the same three rows as slice 1."""
        self.assertIn("oidl-play oidl-book", BOOK)  # the live twelve-risk comparison stays
        self.assertIn("## Risks with items", BOOK)
        self.assertIn("examples/home-risks.csv", BOOK)
        self.assertIn("examples/home-specified-items.csv", BOOK)
        self.assertIn(
            "python3 -m ipngine batch examples/home.ipn examples/home-risks.csv "
            "specified_items=examples/home-specified-items.csv",
            BOOK,
        )
        self.assertIn("[Command line](cli.md)", BOOK)

        code, out = run("batch", str(HOME), str(HOME_RISKS), f"specified_items={HOME_ITEMS}")
        rows = list(csv.DictReader(io.StringIO(out)))
        self.assertEqual(code, 0, out)
        self.assertEqual([r["risk"] for r in rows], ["A", "B", "C"])
        self.assertTrue(all(r["error"] == "" for r in rows), rows)
        a, b, c = (Decimal(r["net"]) for r in rows)
        self.assertLess(b, a)
        self.assertGreater(c, a)

    def test_ac_no_hand_written_page_says_items_cannot_be_batched(self):
        offenders = [
            str(p.relative_to(ROOT)) for p in hand_written_pages() if FORBIDDEN in p.read_text()
        ]
        self.assertEqual(offenders, [])

    def test_ac_price_a_book_states_an_empty_collection_and_declined_rows(self):
        self.assertIn("empty collection", BOOK)
        self.assertIn("requires items", BOOK)  # "a product that requires items declines those rows"
        self.assertIn("declines those rows and", BOOK)

    def test_ac_command_line_shows_the_optional_collection_binding_and_synopsis(self):
        self.assertIn("python3 -m ipngine batch FILE.ipn RISKS.csv [collection=file.csv ...]", CLI)
        self.assertIn("numbered from 1", CLI)  # risk join, row number when omitted
        self.assertIn(
            "python3 -m ipngine batch examples/home.ipn examples/home-risks.csv "
            "specified_items=examples/home-specified-items.csv",
            CLI,
        )
        self.assertIn("declines it and prices it anyway", CLI)  # declined row still priced
        self.assertIn("column on the book whose cell", CLI)  # path-in-cell still works

    def test_ac_reference_getting_started_and_glossary_point_at_the_batch_join(self):
        inputs_ref = (DOCS / "reference" / "inputs.md").read_text()
        self.assertIn("A book gives one\nsuch CSV per collection", inputs_ref)
        self.assertIn("[Command line](../cli.md)", inputs_ref)

        getting_started = (DOCS / "getting-started.md").read_text()
        self.assertIn("second CSV joined on `risk`", getting_started)

        glossary = (DOCS / "glossary.md").read_text()
        self.assertIn(
            "a book prices them from a second CSV joined on `risk`, see [Command line](cli.md)",
            glossary,
        )

    def test_ac_engineering_docs_and_home_examples_name_the_collection_join(self):
        embedding = (DOCS / "embedding.md").read_text()
        self.assertIn("collection file per repeatable input", embedding)
        self.assertIn("text in, CSV out", embedding)

        readme = (ROOT / "README.md").read_text()
        self.assertIn(
            "python3 -m ipngine batch examples/home.ipn examples/home-risks.csv "
            "specified_items=examples/home-specified-items.csv",
            readme,
        )

        home_comment = HOME.read_text()
        self.assertIn("A sample book of three risks sits beside it", home_comment)
        # check remains the last "Run it with" line despite the earlier batch mention
        run_with_lines = [l for l in home_comment.splitlines() if "Run it with:" in l]
        self.assertEqual(run_with_lines, ["# Run it with:  python3 -m ipngine check examples/home.ipn"])

        home_page = (DOCS / "examples" / "home.md").read_text()
        self.assertIn(
            "python3 -m ipngine batch examples/home.ipn examples/home-risks.csv "
            "specified_items=examples/home-specified-items.csv",
            home_page,
        )


if __name__ == "__main__":
    unittest.main()
